#!/usr/bin/env bash
# Update packages
apt-get update

# Install nginx
apt-get install -y nginx

# Create the document root directory fo nginx
mkdir /etc/nginx/html

echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

cat <<EOF > /etc/nginx/sites-available/default
server {
    listen    80;
    listen    [::]:80 default_server;
    root      /etc/nginx/html;
    index     index.html index.htm;

    location  /redirect_me {
        return 301 https://youtu.be/D1v0FNR3-Xc;
    }

    error_page 404 /404.html;
    location = /404.html {
        root    /etc/nginx/html;
        internal;
    }

    add_header X-Served-By $HOSTNAME;
}
EOF

# Test configuration for syntax error
nginx -t

service nginx restart
