#!/usr/bin/env bash
# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

mybalancer=\
"
frontend  myfrontend
    bind *:80
    mode http
    default_backend mybackend

backend mybackend
    balance roundrobin
    server 256728-web-01 54.227.221.46:80 check
    server 256728-web-02 52.86.160.210:80 check
"
echo "$mybalancer" | sudo tee -a /etc/haproxy/haproxy.cfg

# Ensure HAProxy can be enabled using init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
