#!/usr/bin/env bash
# Configure Nginx to listen on port 80 for all active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
sudo service nginx restart
