#!/usr/bin/env bash
# This script displays: To infinity and beyond indefinitely wit a sleep 2 between each iteration
# 			I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

i=1
while [ $i ]; do
	echo "To infinity and beyond"
	sleep 2
done
