#!/usr/bin/env bash
# This script creates an RSA key pair
# Requirements:
# Name of created private key must be school with 4096 bits created and protected by the passphrase betty
ssh-keygen -t rsa -b 4096 -f school -P betty
